-- =============================================================
-- Healthcare Claims Analytics – Oracle Schema
-- Target: Oracle XE 21c / XEPDB1
-- Schema owner: APP
-- =============================================================

-- ---------------------------------------------------------------
-- 1. Clean slate (safe drops)
-- ---------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP VIEW  v_provider_stats    CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW  v_monthly_trend     CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW  v_patient_risk      CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE healthcare_claims   CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE hcc_stage           CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE app_users           CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- ---------------------------------------------------------------
-- 2. Main fact table
-- ---------------------------------------------------------------
CREATE TABLE healthcare_claims (
  id                        NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bene_id                   VARCHAR2(50)    NOT NULL,
  dob                       DATE,
  gender                    NUMBER(1),          -- 1=Male  2=Female
  race                      NUMBER(1),          -- CMS codes: 1=White 2=Other 3=Black 5=Hispanic
  state                     NUMBER(3),          -- CMS state codes (1-51)
  chroniccond_diabetes      NUMBER(1),          -- 1=Yes  2=No
  chroniccond_heartfailure  NUMBER(1),          -- 1=Yes  2=No
  claim_id                  VARCHAR2(50)    NOT NULL,
  claimstartdt              DATE,
  claimenddt                DATE,
  provider                  VARCHAR2(50),
  inscclaimamtreimbursed    NUMBER(12, 2)   DEFAULT 0,
  attendingphysician        VARCHAR2(50),
  admissiondt               DATE,
  dischargedt               DATE,
  created_at                TIMESTAMP       DEFAULT SYSTIMESTAMP,

  CONSTRAINT uq_claim_id UNIQUE (claim_id),
  CONSTRAINT chk_gender  CHECK (gender           IN (1, 2)),
  CONSTRAINT chk_diabetes CHECK (chroniccond_diabetes    IN (1, 2)),
  CONSTRAINT chk_hf       CHECK (chroniccond_heartfailure IN (1, 2))
);

-- ---------------------------------------------------------------
-- 2b. Users table
-- ---------------------------------------------------------------
CREATE TABLE app_users (
  id                        NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email                     VARCHAR2(100)   NOT NULL UNIQUE,
  name                      VARCHAR2(100),
  role                      VARCHAR2(20)    DEFAULT 'Analyst',
  password_hash             VARCHAR2(200)   NOT NULL,
  is_active                 NUMBER(1)       DEFAULT 1,
  created_at                TIMESTAMP       DEFAULT SYSTIMESTAMP,

  CONSTRAINT chk_role CHECK (role IN ('Admin', 'Analyst', 'Viewer'))
);

-- ---------------------------------------------------------------
-- 3. Indexes
-- ---------------------------------------------------------------
CREATE INDEX idx_hcc_bene       ON healthcare_claims (bene_id);
CREATE INDEX idx_hcc_state      ON healthcare_claims (state);
CREATE INDEX idx_hcc_provider   ON healthcare_claims (provider);
CREATE INDEX idx_hcc_claimstart ON healthcare_claims (claimstartdt);
CREATE INDEX idx_hcc_physician  ON healthcare_claims (attendingphysician);

-- ---------------------------------------------------------------
-- 4. Analytical views
-- ---------------------------------------------------------------

-- Provider-level roll-up
CREATE OR REPLACE VIEW v_provider_stats AS
SELECT
  provider,
  COUNT(*)                              AS total_claims,
  COUNT(DISTINCT bene_id)               AS unique_patients,
  SUM(inscclaimamtreimbursed)           AS total_reimbursed,
  ROUND(AVG(inscclaimamtreimbursed), 2) AS avg_reimbursed,
  ROUND(AVG(dischargedt - admissiondt), 1) AS avg_los_days,
  RANK() OVER (ORDER BY COUNT(*) DESC)  AS claim_rank
FROM healthcare_claims
WHERE provider IS NOT NULL
GROUP BY provider;

-- Monthly claim volume + spend
CREATE OR REPLACE VIEW v_monthly_trend AS
SELECT
  TRUNC(claimstartdt, 'MM')            AS claim_month,
  TO_CHAR(claimstartdt, 'YYYY-MM')     AS month_label,
  COUNT(*)                             AS total_claims,
  SUM(inscclaimamtreimbursed)          AS total_reimbursed,
  ROUND(AVG(inscclaimamtreimbursed), 2) AS avg_reimbursed
FROM healthcare_claims
WHERE claimstartdt IS NOT NULL
GROUP BY TRUNC(claimstartdt, 'MM'), TO_CHAR(claimstartdt, 'YYYY-MM')
ORDER BY claim_month;

-- High-risk patients (both chronic conditions)
CREATE OR REPLACE VIEW v_patient_risk AS
SELECT
  bene_id,
  dob,
  gender,
  race,
  state,
  chroniccond_diabetes,
  chroniccond_heartfailure,
  CASE
    WHEN chroniccond_diabetes = 1 AND chroniccond_heartfailure = 1 THEN 'High'
    WHEN chroniccond_diabetes = 1 OR  chroniccond_heartfailure = 1 THEN 'Medium'
    ELSE 'Low'
  END                                                             AS risk_level,
  COUNT(claim_id)                                                 AS total_claims,
  SUM(inscclaimamtreimbursed)                                     AS lifetime_reimbursed
FROM healthcare_claims
GROUP BY
  bene_id, dob, gender, race, state,
  chroniccond_diabetes, chroniccond_heartfailure;
